---
# Enable or disable the application.
cloudflare_ddns_enabled: false

# Cloudflare dynamic DNS Docker container settings.
cloudflare_ddns_container_name: "cloudflare-ddns"
cloudflare_ddns_hostname: "cloudflare-ddns"
cloudflare_ddns_icon_url: "https://github.com/ptoulouse/ansible-unraid/raw/main/icons/cloudflare.png"
cloudflare_ddns_image_version: "latest"
cloudflare_ddns_network: "cloudflare-ddns"
cloudflare_ddns_restart_policy: "{{ docker_restart_policy | default('unless-stopped') }}"
cloudflare_ddns_group_id: "100"
cloudflare_ddns_user_id: "99"

# Cloudflare API token.
cloudflare_ddns_api_token: ""
