---
- name: NAS01 Playbook
  hosts: nas01
  become: true
  gather_facts: false
  roles:
    - role: python_venv
      tags: python_venv
      vars:
        ansible_python_interpreter: "/usr/bin/python3" # Use system Python for initial setup

    # Base Services
    - role: cloudflare_ddns
      tags: cloudflare_ddns
    - role: mail_relay
      tags: mail_relay
    - role: lldap
      tags: lldap
    - role: authelia
      tags: authelia
    - role: traefik
      tags: traefik

    # Monitoring services.
    - role: dozzle
      tags: dozzle
    - role: glances
      tags: glances
    - role: healthchecks
      tags: healthchecks
    - role: scrutiny
      tags: scrutiny

    # E-Books services.
    - role: calibre_web
      tags: calibre_web
    - role: cops
      tags: cops

    # Plex services.
    - role: plex
      tags: plex
    - role: tautulli
      tags: tautulli

    # Other services.
    - role: freshrss
      tags: freshrss
