---
vault_domain_name: "ptoulouse.ca"

vault_admin_password: "4vywgyPIcCG5J4Gm"

# Sender email address for notifications email.
vault_sender_email: "ptoulouse66@gmail.com"

# Cloudflare DDNS settings.
vault_cloudflare_api_token: "mp6v1hvymps3_hSswAlvyVIuo-hL-3S9XULK_XEQ"


# LLDAP settings.
vault_lldap_admin_password: "&19Xkx6#g5V7F%bo"
vault_lldap_jwt_secret: ";u@IeAT,6ZP~=}@c#_2#OAx00GT!4e<N"
vault_lldap_readonly_password: "TyTHhDSmq1EsAQkOev3c05RlaHfum1n0"

# Authlia settings.
vault_authelia_identity_jwt_secret: ".r0eFWdfA9'uT(9pgrM,5gIkoCtWn?P!"
vault_authelia_oidc_hmac_secret: "Q5Y5Uw6Ub2wL0kxeWIxvWIwcu1E3bgRuc1H9dvTvYt8O450B8kM0E40tSL1pmgVB"
vault_authelia_identity_providers_oidc_jwks_key: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIJKQIBAAKCAgEArC8xyvaz8DVRZ+aJw3BH4DHBYOTr0bemKVEip+y4nA41Lsjy
  O3Ai35v+saFOfqhoRG7Twlw6I/ZzAo5WazsVXFYEszoLRqX98otlHpLBYNId/Gim
  kVXJEKFvTEOWRNwowDDUouFVx/dNwGCXHwHuo/2kIr0ZVtAA0A5kQ44yDRPp3TJ+
  ZLq/VsObXzwuwzS0AMfPkZkiKLoBL7X4X27MnmocHNABZlPtg/VQriTKXM0AUT01
  gwmDAy8p7NmZRpptDhUSJgSYob4L6cpd5N4m6ID4QR2SZ+a6EbjW8sDc6aF7KKkr
  QpJ8AvYB6+P70aK7i+94NswVNXus4giEP7SpQ0CI4ayxcVyaS9JBLe8Z9azJLHrK
  4AF5LDViMrCL6PH3ZXg6i98xQhRbBlzEuQw8jTOuCzQcw1IRw1UrUERhEgaGid4G
  o7bNgIPNpr5hmucfx4VsjhH2JJimzSKAg4XbV3oHRUFi4wUtQMHSxbtk2DnCn0Dr
  4/QVtpX5+7R1XfOrmsdVfFbaIL1D1vGJ/IIC9B6j/NF9YwpO/2BnN0ZZosMKcqkv
  8l1a3oZizJ9TV86SMTZiica3+BzV5Ke3Jfzer9qshi98nI1NKeQjjaM9VF16ul5t
  +hoYZ69KnpaN2BlKcn+Fo3c8V7mRn6dRQkWMScQA+e0Np//Y3Ymyeo6PedcCAwEA
  AQKCAgBJ27SwK0LkNvrEZs+RVgh+0tjwh0Hgo7ZS4srK3XATAMUvXGMLu/45jOCj
  sV3KVtLjB+ct6AHIi16qKgRH2wA+q2c4uh08INfdwo2Nn8Xzki3qp7lLflDRIW5s
  eFFtGEMirc+ITsBNFnfznXs1gc6r6ZEOla7Y3kB6/rFjiQtPMMuQZqhw7OpGfYGY
  SGiGs4TDEPKosddFQQRhQt1Xkl+TVFDayx7OlhG8GO6SxJVJWWZZcrgRjXL1WrXR
  M0XcU0GUWNWAGVifiLXzgyrjkad+9FOJGvZCO2Z1U6RgXPpl/S6nMmmsFMm9O2l3
  lkPemL96Ny6J0uEGIBb4nk6cRRKVYf1JHjLwRqHAYimX5BdnnGEcGivzC2GuONTB
  lNyfMOoPRmVZwJL0SmXNYECF6oV66nuCl+tT7KY7FHdD8CuIpW8GIeUYEW4Mtqrk
  uw0I6dTLZ9hwnNq+sFOVyx0mm9kp5TKm2wBzRMZdwUzxAmu/3zLuYYhiypiRjn6Z
  hgjsHv0xwY57PB2xfP/IxjAqMpxD2RlgBqQTr3sXw8LGWZeasGGnU4YxY0EtnCqu
  okI3byXkEJfMJSU7XtBLsmPFHSQaY9rygptD6J+26G888gPfborjDNGFjMun2NQk
  hRv2cuWV9Xx8zoNCRS76m7ZYqW7sEE5ooW1Gp2mWI8vWXbynAQKCAQEA4PB0e1D6
  emDcwBrnuo2/fcjoLWC1MS9bWMk9ziCR3vHN2kp56xfPq9nP5OdAZ7ER0dX/vByM
  +7ltXGjkxegYY2zO3JJ4kyKxD5C+WRjukUpDxzJSR1e0SsZqDIK0jfNcg4dfVROo
  vyXWjK82K6hJgWjFm8/lr3kQSvx3ESMij9GrCNBzNVKQwxZ56lDdVsA6LVfyUog4
  N7HEEIYbeRdb+5AdWjaYbrHABEamucZlcifsZcUmeKOyVi+6yUi0udqzX8spZic6
  RTlTKEhQWhyMMcYR0RgE8lsJ4HBcQ33R4TCV9pShBOjCCW38eGyuoJGm0zmghjnW
  AuAyOx6LIJuiPwKCAQEAw/Xd3MJkADh+6rgIAt6Sq6SwKl9pG5LfC3yYa9Vf/A/v
  eL3NILboTlT+dpKrZHo9UCfFWrvFDbFKN9PT5TKqgvncp5k7Zg1SizCQoNw775JM
  Qsg3hJP9GRyBsgMvDOOz3/J04QYZu/XoUQQ2sEIAH3us357LiUe9ZTckuSeFexQ1
  /AEO3NJ5u6i4nvbSy57lwBMiPs+gqfllSO9w7OUiIpNS7hqsKxqdJfNAu98uO4K3
  tyeLQWP3pHLHyU8xlNERPjgkto7gkg/DbUQ+ALTNiixEF7Y+5W8U6m1MJePqsRIO
  /jXCrJtovBNSEzNct2oMlQlFcR5YuH0iqVUww06SaQKCAQEAsoPCPZevoW274622
  mCQkg8PtFw433jfyK81SAoNwoNmQABy5Ey1Lf9wVlFk+kMxDEx/dnEGgVan8M6l/
  XdzrdgSFSyHnFQYkNPEvT3Bs7NteXPj/uWTOTcWXpiQY/MrVcgD+VHuMoV57Hh1z
  RUSCSXSH1zcv1omit5ATQoN6y16feRhNRlUnU9xDlwTkFBPsV84DHyLCUtj+fAqi
  RQCX3FasJMtNQBRLClmzuZ3NJsKuZroG5Rks0B+DAnl0DEeXsX9/dHXPVd6/sylo
  s4sSa/IAc8u3KUu80+T4JAv3g9rWOOINw+KhE3C5PC0sjXvqRJnoXn4J7TBWTPrZ
  eWBqawKCAQBlIVgUfAXbz0xAmiUYRgFvr5hy5bZ60ntllDGdRQs6LIcrytg4D+0n
  r9l7HApz2loWKdBCGTGC9YIV+a4bVOCGo6hqnjv3WNzGlJOvULll1ByjQmzUcQNn
  mDyev+HiRwknhBspnlpdlHUGiqQmpokltk/rQCpOeMWXnLPJEkpi0HVjzq/66myE
  mnhdIYh8KU7sp3M+8yw5TEonL9sZhs7tBRcBZqZ/wEZltXos+usDL1zcmv3VC2Bc
  cBgHHmW6JYM+lv7rcCUZfCUhGNzexHBm5J1nl1gyU/d5XFq2Gz+djnJKYzhKmBGf
  LmFnI1SwG3zO1XAPBthGrd3bgemegcgxAoIBAQCBK1LoRNoibVUqMwZD46rIAFxu
  hig12G15i6OO3PzLyGm63DWGz3lIqMWPUTcFB8/zpVss8CxQ30kNCZXZ6w8I2jJg
  GVHiMqoLcmPLuSiEeYx9XdzpPW2jSfao2QRBAuQbaG1psq85UF+wpyILJvK/c3Ka
  hqyQFhnM2zo/oAYgTX/G9zk8pf41UK+yMnIk9Hbj8JedCCqbJyoc1RfJou06hYvF
  DbA4mHL6Ydt2asZ3nfIG21vyzsbjqEGeh87BJhKAqyonXA8+AR6qiGqyOb3iIZHw
  g4ekBmtWjquXeH0P4aHjWx/ohceurPeELHOeKgKz6aegtkl8gfXCRuI5K3Us
  -----END RSA PRIVATE KEY-----

vault_authelia_storage_encryption_key: "aquELX3bdS7tKKJHB9gaGL0IVnKDyzZnRZNjzFnreYgX1ZIwqK5894g049Mv1N4b"

# Mail Relay settings.
vault_mail_relay_smtp_username: "ptoulouse66@gmail.com"
vault_mail_relay_smtp_password: "rhwbxhzznkaegyxy"

# Healthchecks settings.
vault_healthchecks_secret_key: "xNNdUvGC1g0H6c1vs4yvCOXkLBV0zPYIZa3lV06Mfn02XVboJf"

# Bookstack settings.
vault_bookstack_oidc_id: "whKwbHVBQp6igbRBQhoGjHZoOHubVTxTSwVcQNUV2Z3Mh9o3bFL6CSXlxV2m11PAvbnDk9Ab"
vault_bookstack_oidc_secret: "$pbkdf2-sha512$310000$MDXhSSTHiecRtJg4E79shg$nUIrG3iLajamIYiQp3GIKJf\
                             3aXcs5c9V9sHB3EmN3RWxnZBSfraQGnnXKmy8vVz4k7A7EugToPLWqJ8NSEOMow"

# Nextcloud settings.
vault_nextcloud_oidc_id: "plGYOtZgfF21JbqglAPSnX0JwcbvmNIMjvccqCi9nb01RcL2htXWAnTEdNU00N9JJ7WXXUe1"
vault_nextcloud_oidc_secret: "$pbkdf2-sha512$310000$WFHoPj1Yp0Ps/pVMJ5e/QQ$f0VLfI01J1frG2lSkK7T7Nd\
                             3C5sPyDcyt0MGmHOVuNojsChrZ2UE9wJ4thBXjEBqzmOybHVXOG7uQevQYh4Png"
