---
- name: Start Open-WebUI
  when: open_webui_enabled is true
  block:
    - name: Check that required variables are defined.
      ansible.builtin.assert:
        that:
          - item | length > 0
        fail_msg: "{{ item }} is not defined."
      loop:
        - open_webui_secret_key

    - name: Create Open-WebUI directories
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: directory
        owner: "{{ item.owner | default('root') }}"
        group: "{{ item.group | default('root') }}"
        mode: "{{ item.mode | default('0750') }}"
      loop:
        - path: "{{ open_webui_data_path }}"
        - path: "{{ open_webui_data_path }}/config"

    - name: Create Open-WebUI Docker Container
      community.docker.docker_container:
        name: "{{ open_webui_container_name }}"
        image: "ghcr.io/open-webui/open-webui:{{ open_webui_image_version }}"
        pull: true
        restart_policy: "{{ open_webui_restart_policy }}"
        networks:
          - name: "{{ ollama_network }}"
          - name: "{{ traefik_network }}"
        volumes:
          - "{{ open_webui_data_path }}/config:/app/backend/data"
        env:
          OLLAMA_BASE_URL: "{{ open_webui_ollama_url }}"
          WEBUI_SECRET_KEY: "{{ open_webui_secret_key }}"
        labels:
          folder.view2: "AI"
          net.unraid.docker.icon: "{{ open_webui_icon_url }}"
          net.unraid.docker.managed: "dockerman"
          net.unraid.docker.shell: bash
          net.unraid.docker.webui: "https://{{ open_webui_hostname }}.{{ open_webui_domain }}"
          traefik.enable: "true"
          traefik.http.routers.open_webui.entrypoints: "https"
          traefik.http.routers.open_webui.middlewares: "auth-chain@file"
          traefik.http.routers.open_webui.rule: "Host(`{{ open_webui_hostname }}.{{ open_webui_domain }}`)"
          traefik.http.routers.open_webui.service: "open_webui"
          traefik.http.services.open_webui.loadbalancer.server.port: "8080"
        security_opts:
          - no-new-privileges:true

- name: Stop Open-WebUI
  when: open_webui_enabled is false
  block:
    - name: Stop Open-WebUI
      community.docker.docker_container:
        name: "{{ open_webui_container_name }}"
        state: absent
