---
# Enable or disable the application.
dozzle_enabled: false

# Dozzle Docker container settings.
dozzle_container_name: "dozzle"
dozzle_hostname: "dozzle"
dozzle_icon_url: https://github.com/walkxcode/Dashboard-Icons/raw/main/png/dozzle.png
dozzle_image_version: "latest"
dozzle_restart_policy: "{{ docker_restart_policy | default('unless-stopped') }}"
