---
# User on remote host. Unraid has only one user: root.
ansible_user: "root"

# Python interpreter to use on the remote host.
ansible_python_interpreter: "{{ python_venv_path }}/bin/python3"

# Domain name for services.
domain_name: "{{ vault_domain_name }}"

# Unraid server hostname.
server_name: "nas01"

timezone: "America/Montreal"

# Default initial admin password for services.
admin_password: "{{ vault_admin_password }}"

# Sender email address for notifications email.
sender_email: "{{ vault_sender_email }}"

# Shares paths.
books_path: "/mnt/user/media/libraries/books"
media_path: "/mnt/user/media"
photos_path: "/mnt/user/photos"

# Path where Python virtual environment will be created.
python_venv_path: /mnt/user/appdata/python_venv

# Python packages to install in the virtual environment.
python_venv_packages:
  - docker
  - passlib
  - bcrypt
  - requests

# Override default Docker restart policy.
docker_restart_policy: "always"

# Path where Docker containers will store their data.
docker_data_path: "/mnt/user/appdata"

# Enable or disable applications.
authelia_enabled: true
calibre_web_enabled: true
cloudflare_ddns_enabled: true
cops_enabled: true
dozzle_enabled: true
freshrss_enabled: true
glances_enabled: true
healthchecks_enabled: true
lldap_enabled: true
mail_relay_enabled: true
plex_enabled: true
scrutiny_enabled: true
tautulli_enabled: true

# Cloudflare DDNS settings.
cloudflare_ddns_api_token: "{{ vault_cloudflare_api_token }}"

# Mail Relay settings.
mail_relay_smtp_server: "smtp.gmail.com"
mail_relay_smtp_port: "587"
mail_relay_smtp_username: "{{ vault_mail_relay_smtp_username }}"
mail_relay_smtp_password: "{{ vault_mail_relay_smtp_password }}"

# LLDAP settings.
lldap_admin_password: "{{ vault_lldap_admin_password }}"
lldap_jwt_secret: "{{ vault_lldap_jwt_secret }}"
lldap_readonly_password: "{{ vault_lldap_readonly_password }}"

# Authelia settings.
authelia_identity_jwt_secret: "{{ vault_authelia_identity_jwt_secret }}"
authelia_oidc_hmac_secret: "{{ vault_authelia_oidc_hmac_secret }}"
authelia_identity_providers_oidc_jwks_key: "{{ vault_authelia_identity_providers_oidc_jwks_key }}"
authelia_storage_encryption_key: "{{ vault_authelia_storage_encryption_key }}"

authelia_access_control_rules:
  - domain:
      - "{{ authelia_hostname }}.{{ domain_name }}"
      - "{{ plex_hostname }}.{{ domain_name }}"
      - "{{ nextcloud_hostname }}.{{ domain_name }}"
    policy: bypass
  - domain:
      - "{{ homepage_hostname }}.{{ domain_name }}"
    resources:
      - '^/site.webmanifest.*'
    policy: bypass
  - domain:
      - "{{ healthchecks_hostname }}.{{ domain_name }}"
    resources:
      - '^/ping/.+'
    policy: bypass
  - domain:
      - "{{ calibre_web_hostname }}.{{ domain_name }}"
      - "{{ cops_hostname }}.{{ domain_name }}"
    subject:
      - group:ebooks_users
    policy: one_factor
  - domain:
      - '*.{{ domain_name }}'
    subject:
      - group:admin
    policy: two_factor

authelia_oidc_clients:
  - client_id: "{{ vault_bookstack_oidc_id }}"
    client_name: 'BookStack'
    client_secret: "{{ vault_bookstack_oidc_secret }}"
    public: "false"
    redirect_uris:
      - 'https://{{ bookstack_hostname }}.{{ domain_name }}/oidc/callback'
    scopes:
      - 'openid'
      - 'groups'
      - 'email'
      - 'profile'
    authorization_policy: 'two_factor'
    userinfo_signed_response_alg: 'none'
  - client_id: "{{ vault_nextcloud_oidc_id }}"
    client_name: 'Nextcloud'
    client_secret: "{{ vault_nextcloud_oidc_secret }}"
    public: "false"
    redirect_uris:
      - 'https://{{ nextcloud_hostname }}.{{ domain_name }}/apps/user_oidc/code'
    scopes:
      - 'openid'
      - 'groups'
      - 'email'
      - 'profile'
    authorization_policy: 'two_factor'
    consent_mode: 'implicit'
    require_pkce: "true"
    pkce_challenge_method: 'S256'
    userinfo_signed_response_alg: 'none'
    token_endpoint_auth_method: 'client_secret_post'

# Healthchecks settings.
healthchecks_secret_key: "{{ vault_healthchecks_secret_key }}"

# Scrutiny settings.
scrutiny_devices:
  - /dev/disk/by-id/ata-Samsung_SSD_860_EVO_500GB_S59UNMFN804153R:/dev/sdf
  - /dev/disk/by-id/nvme-WDS500G3X0C-00SJG0_20408A804512:/dev/nvme0
  - /dev/disk/by-id/ata-WDC_WD80EDBZ-11B0ZA0_VRGJ5PSK:/dev/sdc
  - /dev/disk/by-id/ata-WDC_WD80EMZZ-11B4FB0_WD-CA03PHHG:/dev/sdd
  - /dev/disk/by-id/ata-WDC_WD80EMZZ-11B4FB0_WD-CA036WZG:/dev/sde
scrutiny_port: "8081"

###### TEMPORARY ######
nextcloud_hostname: "nextcloud"
homepage_hostname: "homepage"
authelia_hostname: "auth"
bookstack_hostname: "bookstack"
