---
- name: Start Glances
  when: glances_enabled is true
  block:
    - name: Create Glances Docker Container
      community.docker.docker_container:
        name: "{{ glances_container_name }}"
        image: "nicolargo/glances:{{ glances_image_version }}"
        pull: true
        restart_policy: "{{ glances_restart_policy }}"
        networks:
          - name: "{{ traefik_network }}"
        volumes:
          - "/var/run/docker.sock:/var/run/docker.sock:ro"
          - "/etc/timezone:/etc/timezone:ro"
        env:
          GLANCES_OPT: "-w"
        labels:
          folder.view2: "Monitoring"
          net.unraid.docker.icon: "{{ glances_icon_url }}"
          net.unraid.docker.managed: "dockerman"
          net.unraid.docker.shell: "bash"
          net.unraid.docker.webui: "https://{{ glances_hostname }}.{{ domain_name }}"
          traefik.enable: "true"
          traefik.http.routers.glances.entrypoints: "https"
          traefik.http.routers.glances.middlewares: "auth-chain@file"
          traefik.http.routers.glances.rule: "Host(`{{ glances_hostname }}.{{ domain_name }}`)"
          traefik.http.routers.glances.service: "glances"
          traefik.http.services.glances.loadbalancer.server.port: "61208"
        privileged: true
        security_opts:
          - no-new-privileges:true
        pid_mode: host

- name: Stop Glances
  when: glances_enabled is false
  block:
    - name: Stop Glances
      community.docker.docker_container:
        name: "{{ glances_container_name }}"
        state: absent
