---
- name: Start Authelia
  when: authelia_enabled is true
  block:
    - name: Check that required variables are defined.
      ansible.builtin.assert:
        that:
          - item | length > 0
        fail_msg: "{{ item }} is not defined."
      loop:
        - authelia_domain
        - authelia_jwt_secret
        - authelia_lldap_readonly_password
        - authelia_oidc_hmac_secret
        - authelia_oidc_private_key
        - authelia_smto_address
        - authelia_smtp_sender
        - authelia_storage_encryption_key

    - name: Create authelia directories
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: directory
        owner: "{{ item.owner | default('root') }}"
        group: "{{ item.group | default('root') }}"
        mode: "{{ item.mode | default('0750') }}"
      loop:
        - path: "{{ authelia_data_path }}"
        - path: "{{ authelia_data_path }}/config"
          owner: "{{ authelia_user_id }}"
          group: "{{ authelia_group_id }}"

    - name: Create Authelia configuration file
      ansible.builtin.template:
        src: "configuration.yml.j2"
        dest: "{{ authelia_data_path }}/config/configuration.yml"
        owner: "{{ authelia_user_id }}"
        group: "{{ authelia_group_id }}"
        mode: "0600"
        lstrip_blocks: true
      register: authelia_config_file

    - name: Create authelia Docker Container
      community.docker.docker_container:
        name: "{{ authelia_container_name }}"
        image: "authelia/authelia:{{ authelia_image_version }}"
        recreate: "{{ authelia_config_file is changed }}"
        pull: true
        restart_policy: "{{ authelia_restart_policy }}"
        networks:
          - name: "{{ mail_relay_network }}"
          - name: traefik
        volumes:
          - "{{ authelia_data_path }}/config:/config"
        env:
          AUTHELIA_IDENTITY_PROVIDERS_OIDC_ISSUER_PRIVATE_KEY: "{{ authelia_oidc_private_key }}"
          PGID: "{{ authelia_group_id }}"
          PUID: "{{ authelia_user_id }}"
          TZ: "{{ timezone }}"
        labels:
          folder.view2: "Base Services"
          net.unraid.docker.icon: "{{ authelia_icon_url }}"
          net.unraid.docker.managed: "dockerman"
          net.unraid.docker.shell: bash
          net.unraid.docker.webui: "https://{{ authelia_hostname }}.{{ authelia_domain }}"
          traefik.enable: "true"
          traefik.http.routers.authelia.entrypoints: "https"
          traefik.http.routers.authelia.middlewares: "auth-chain@file"
          traefik.http.routers.authelia.rule: "Host(`{{ authelia_hostname }}.{{ authelia_domain }}`)"
          traefik.http.routers.authelia.service: "authelia"
          traefik.http.services.authelia.loadbalancer.server.port: "9091"
        security_opts:
          - no-new-privileges:true

- name: Stop authelia
  when: authelia_enabled is false
  block:
    - name: Stop authelia
      community.docker.docker_container:
        name: "{{ authelia_container_name }}"
        state: absent
