---
- name: Start Calibre-Web
  when: calibre_web_enabled is true
  block:
    - name: Create Calibre-Web directories
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: directory
        owner: "{{ item.owner | default('root') }}"
        group: "{{ item.group | default('root') }}"
        mode: "{{ item.mode | default('0750') }}"
      loop:
        - path: "{{ calibre_web_data_path }}"
        - path: "{{ calibre_web_data_path }}/config"
          owner: "{{ calibre_web_user_id }}"
          group: "{{ calibre_web_group_id }}"

    - name: Create Calibre-Web Docker Container
      community.docker.docker_container:
        name: "{{ calibre_web_container_name }}"
        image: "lscr.io/linuxserver/calibre-web:{{ calibre_web_image_version }}"
        pull: true
        restart_policy: "{{ calibre_web_restart_policy }}"
        networks:
          - name: "{{ mail_relay_network }}"
          - name: traefik
        volumes:
          - "{{ books_path }}:/books"
          - "{{ calibre_web_data_path }}/config:/config"
        env:
          DOCKER_MODS: "linuxserver/calibre-web:calibre"
          PGID: "{{ calibre_web_group_id }}"
          PUID: "{{ calibre_web_user_id }}"
          TZ: "{{ timezone }}"
        labels:
          folder.view2: "E-Books"
          net.unraid.docker.icon: "{{ calibre_web_icon_url }}"
          net.unraid.docker.managed: "dockerman"
          net.unraid.docker.shell: bash
          net.unraid.docker.webui: "https://{{ calibre_web_hostname }}.{{ calibre_web_domain }}"
          traefik.enable: "true"
          traefik.http.routers.calibre-web.entrypoints: "https"
          traefik.http.routers.calibre-web.middlewares: "auth-chain@file"
          traefik.http.routers.calibre-web.rule: "Host(`{{ calibre_web_hostname }}.{{ calibre_web_domain }}`)"
          traefik.http.routers.calibre-web.service: "calibre-web"
          traefik.http.services.calibre-web.loadbalancer.server.port: "8083"
        security_opts:
          - no-new-privileges:true

- name: Stop Calibre-Web
  when: calibre_web_enabled is false
  block:
    - name: Stop Calibre-Web
      community.docker.docker_container:
        name: "{{ calibre_web_container_name }}"
        state: absent
